export function generateSEO(title: string) {
  return {
    slug: title.toLowerCase().replaceAll(" ", "-"),
    metaTitle: title,
    metaDescription: title + " - generated by AI CMS"
  }
}

export function suggestTags(content: string) {
  return ["ai", "cms", "blog"]
}

export function improveText(text: string) {
  return text + " (improved by AI)"
}
